### ISSUE TITLE
Abstract the type scale

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise.css#198]
The new way of setting font sizes is more correct but is not very clean in code.

ref: https://github.com/ConciseCSS/concise.css/issues/194

---

Could be something like:

```scss
.heading {
  // Main scale
  font-size: 5sc;

  // Secondary scale
  font-size: 5scs;
}
```

Which would set the font size with the 5th size in the corresponding scale.
