### ISSUE TITLE
Delete margin for first paragraphs

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise.css#207]
```
Heading
P <- Shouldn't have margin
P
Heading
P <- Shouldn't have margin
P
Xelement
P <- Shouldn't have margin
```

**Comment by jameskolce** [comment]
```css
p {
  margin: 0;
}

p + p {
  margin-top: 1lh;
}
```

**Comment by jameskolce** [comment]
Better:
```scss
h1, h2, h3, h4, h5, h6 {
  & + p {
    margin-top: 0;
  }
}
```
