### ISSUE TITLE
How to define columns for different breakpoints?

### ISSUE THREAD

**Issue by Limboistik** [ConciseCSS/concise.css#208]
Hello!

Is it possible to define the columns for different breakpoints like you can in Bootstrap or Foundation?

ie: If I want the div to take up different columns at different breakpoints: column-sm="12" column-lg="6"?

**Comment by jameskolce** [comment]
Hey @Limboistik! Yeah, is possible, do for example this:

```scss

@media (--large) {
  @for $i from 1 through $num-columns {
    [#{$prefix}column~=lg-"#{$i}"] {
      flex: 0 1 ($i/$num-columns) * 100%;
      max-width: ($i/$num-columns) * 100%;
    }
  }
}
```

Then you can use it like:

```html
<div column="6 lg-6"></div>
```

I hope that helps as a guide, but if you have some other issue just let me know!

**Comment by jameskolce** [comment]
But the way I didn't tested it so let me know if it doesn't work haha

**Comment by Limboistik** [comment]
Ah I see thank you.

My Sass is not that good ;-), so I was hoping it was pre-setup in Concise as simply column classes I can just apply to a div ala Bootstrap/Foundation.

Thanks though!

**Comment by jameskolce** [comment]
Yeah, I decided to not do that to follow the **concise** philosophy, and provide just the minimal do work with. But doing something like what I mentioned should work!

And no problem, if you have any other issue just let me know!

**Comment by jameskolce** [comment]
@Limboistik Oh sorry sorry, I just noticed that I posted code from the currently on development version (v4) and not the current one (v3), in that case would be like this:

```scss
@media (min-width: $bp-large) {
    // Create columns
    @for $i from 1 through $num-columns {
      [#{$prefix}column~="lg-#{$i}"] {
        width: (($i / $num-columns) * 100%);
      }
    }
  }
```
