### ISSUE TITLE
Fix abbr styles

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise.css#211]
- Delete underlined style
- Add dotted bottom border
- Add question cursor

**Comment by jameskolce** [comment]
```scss
abbr[title] {
  text-decoration: none;
  border-bottom: 1px dotted getColor(base, lines);
  cursor: help;
}
```
