### ISSUE TITLE
_forms.scss improvements (for radio and checkbox)

### ISSUE THREAD

**Issue by FredHall** [ConciseCSS/concise.css#260]
This change will likely need to be delayed until the next major release as it changes some default behavior. 

Goals:
---------------------------------------------
1) support <label><input></label> syntax
2) support inline inputs

Sample HTML
---------------------------------------------
```html
<form action="action_page.php">
  <div grid="ng">
    <div column="6">
      <label>Gender: input label</label>
      <input id="male" type="radio" name="gender" value="Male"><label for="male">Male</label>
      <input id="female" type="radio" name="gender" value="Female"><label for="female">Female</label>
    </div>
    <div column="6">
      <label>Gender: label input</label>
      <label><input type="radio" name="gender2" value="male" checked>Male</label>
      <label><input type="radio" name="gender2" value="female">Female</label>
    </div>
  </div>
  <div grid="ng">
    <div column="6" class="_inline">
      <h5>Inline: Gender: input label</h5>
      <input id="male2" type="radio" name="gender3" value="Male"><label for="male2">Male</label>
      <input id="female2" type="radio" name="gender3" value="Female"><label for="female2">Female</label>
    </div>
    <div column="6" class="_inline">
      <h5>Inline: label input</h5>
      <label><input type="radio" name="gender4" value="male" checked>Male</label>
      <label><input type="radio" name="gender4" value="female">Female</label>
    </div>
  </div>

  <div grid="no-gutter">
    <div column="6">
    <h5>input label</h5>
    <input id="bike" type="checkbox" name="vehicle1" value="Bike"><label for="bike">I have a bike</label>
    <input id="car" type="checkbox" name="vehicle2" value="Car"><label for="car">I have a car</label>
    </div>
    <div column="6">
    <h5>label input</h5>
    <label><input type="checkbox" name="transport1" value="Bike" checked>I have a bike</label>
    <label><input type="checkbox" name="transport2" value="Car">I have a car</label>
    </div>
  </div>

  <div grid="ng">
    <div column="6" class="_inline">
    <h5>Inline: input label</h5>
    <input id="bike2" type="checkbox" name="vehicle3" value="Bike"><label for="bike2">I have a bike</label>
    <input id="car2" type="checkbox" name="vehicle4" value="Car"><label for="car2">I have a car</label>
    </div>
    <div column="6" class="_inline">
    <h5>Inline: label input</h5>
    <label><input type="checkbox" name="transport3" value="Bike" checked>I have a bike</label>
    <label><input type="checkbox" name="transport4" value="Car">I have a car</label>
    </div>
  </div>
  
  <input type="submit" value="Submit">
  <button> y submit?</button>
</form> 
```

Changes made
---------------------------------------------
concise.css/src/_forms.scss
```diff
Line 11
--   min-height: 1.5lh;
++   //min-height: 1.5lh;

Line 43
++   margin-bottom: 0.1lh;

Line 75
--   display: block;

Line 80
-- // Labels are inline with their checkbox and radio elements
++ // Inputs before label.

Line 83
--   display: inline-block;
```
Added to the end of the file...
```diff
++  // Inputs inside label.
++  label > input[type="radio"],
++  label > input[type="checkbox"] {
++    margin-right: 0.5em;
++  }
++  
++  // If not inline, then add a line break
++  :not(._inline) > label:after {
++    content: "\A";
++    white-space: pre;
++  }
++  
++  div._inline > label {
++    margin-right:1.5em;
++  }
```
![chrome](https://cloud.githubusercontent.com/assets/24819365/21905141/ae76a9d4-d8c3-11e6-97f9-99f19dec054d.png)
![firefox](https://cloud.githubusercontent.com/assets/24819365/21905140/ae73c78c-d8c3-11e6-996f-ce78e32ffde1.png)
![ie11](https://cloud.githubusercontent.com/assets/24819365/21905143/ae7cee20-d8c3-11e6-8888-610021560355.png)
![safari](https://cloud.githubusercontent.com/assets/24819365/21905142/ae7813a0-d8c3-11e6-943d-c16517ca3d03.png)

Modified File
---------------------------------------------
concise.css/src/_forms.scss
```scss
//
// Forms
// =============================================================================

input:not([type="submit"]),
select,
textarea {
  transition-duration: $transition-duration;
  width: 100%;
  font-size: typeScale(1);
  // min-height: 1.5lh;

  &:focus {
    border-color: getColor(blue, lighter);
  }

  &[disabled] {
    background-color: getColor(state, muted);
    cursor: not-allowed;
    border: 0;
  }
}

input:not([type="submit"]):not([type="range"]),
select,
textarea {
  border: 1px solid getColor(base, lines);
  padding: 0 0.75em;
}

input[type="checkbox"],
input[type="file"],
input[type="image"],
input[type="radio"] {
  height: auto;
  width: auto;
}

input[type="checkbox"],
input[type="radio"] {
  line-height: normal;
  padding: 0;
  vertical-align: middle;
  margin-bottom: 0.1lh;
}

input[type="file"] {
  border: none;
  line-height: 1lh;
  padding: 0;
}

select {
  background-color: transparent;
  padding-left: 0.5em;
  width: auto;
  min-width: 10em;
  height: 1.5lh;

  &[disabled] { color: getColor(text, secondary); }

  &[multiple] {
    height: auto;
    width: 100%;
    padding: 0;
  }

  &::-ms-expand { display: none; }

  &::-ms-value { color: currentColor; }

  option { padding: 0 0.75em }
}

label {
  font-size: typeScale(1);
  line-height: 1.5lh;
}

// Inputs before label.
input[type="checkbox"] + label,
input[type="radio"] + label {
  margin-left: 0.5em;
}

// Inputs inside label.
label > input[type="radio"],
label > input[type="checkbox"] {
  margin-right: 0.5em;
}

// If not inline, then add a line break
:not(._inline) > label:after {
  content: "\A";
  white-space: pre;
}

div._inline > label {
  margin-right:1.5em;
}
```
