### ISSUE TITLE
Simplify the font families

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise.css#266]
```scss
h1 {
  font-family: heading;
}

body {
  font-family: body;
}

code {
  font-family: monospaced;
}
```
