### ISSUE TITLE
Overflow on `[container]` breaks `position: sticky`

### ISSUE THREAD

**Issue by brianmhunt** [ConciseCSS/concise.css#272]
The `overflow: auto` on `[container]` prevents one from using `position: sticky`.

This simple example should demonstrate the problem; remove the `overflow` property from the `main` :

```html
<body>
  <main container>
    <section grid> 
      <label column='2' style='position: sticky; top: 5px'>
           Sticky?
      </label>
       <article column='10' style='height: 500px'>
       </article>
    </section>
  </main>
</body>
```

Here's a [basic jsFiddle](https://jsfiddle.net/4frwwgtn/) demonstrating the problem -- comment/uncomment the `overflow: hidden` to see.

The relevant wording from [the spec/discussion](http://www.coreyford.name/files/position-sticky-presentation/):

> The box’s position depends on its containing block (established as for position:static) as well as its scrolling container, defined by the nearest ancestor in the same document with a computed value for ‘overflow-x’ or ‘overflow-y’ other than ‘visible’, or the viewport if no such ancestor exists.

Will post if I figure out a workaround.

**Comment by jameskolce** [comment]
Hi @brianmhunt Thanks for opening the issue, and sorry for the delay.

Indeed `overflow: auto` shouldn't be there, it solved a previous bug but creates the one you mention. 

To fix it in your project you can set:

```scss
[container] {
  overflow: visible; // I think 'visible' is the default value, 'initial' might work too.
}
```

Then, if you get a space at the top of the page, you can do this to remove it:

```scss
:root {
  background-color: transparent;
}

body { 
  background-color: getColor(background, body);
}
```

That should fix everything.
